const defaultFill = '#90A4AE';

const statesDefaults = {
  'AL': { fillColor: defaultFill, value: 35 },
  'AK': { fillColor: defaultFill, value: 24 },
  'AZ': { fillColor: defaultFill, value: 53 },
  'AR': { fillColor: defaultFill, value: 34 },
  'CA': { fillColor: defaultFill, value: 87 },
  'CO': { fillColor: defaultFill, value: 64 },
  'CT': { fillColor: defaultFill, value: 65 },
  'DE': { fillColor: defaultFill, value: 23 },
  'FL': { fillColor: defaultFill, value: 76 },
  'GA': { fillColor: defaultFill, value: 70 },
  'HI': { fillColor: defaultFill, value: 21 },
  'ID': { fillColor: defaultFill, value: 20 },
  'IL': { fillColor: defaultFill, value: 65 },
  'IN': { fillColor: defaultFill, value: 43 },
  'IA': { fillColor: defaultFill, value: 23 },
  'KS': { fillColor: defaultFill, value: 23 },
  'KY': { fillColor: defaultFill, value: 22 },
  'LA': { fillColor: defaultFill, value: 34 },
  'ME': { fillColor: defaultFill, value: 26 },
  'MD': { fillColor: defaultFill, value: 48 },
  'MA': { fillColor: defaultFill, value: 58 },
  'MI': { fillColor: defaultFill, value: 43 },
  'MN': { fillColor: defaultFill, value: 34 },
  'MS': { fillColor: defaultFill, value: 22 },
  'MO': { fillColor: defaultFill, value: 27 },
  'MT': { fillColor: defaultFill, value: 19 },
  'NE': { fillColor: defaultFill, value: 20 },
  'NV': { fillColor: defaultFill, value: 30 },
  'NH': { fillColor: defaultFill, value: 28 },
  'NJ': { fillColor: defaultFill, value: 45 },
  'NM': { fillColor: defaultFill, value: 26 },
  'NY': { fillColor: defaultFill, value: 72 },
  'NC': { fillColor: defaultFill, value: 69 },
  'ND': { fillColor: defaultFill, value: 19 },
  'OH': { fillColor: defaultFill, value: 68 },
  'OK': { fillColor: defaultFill, value: 20 },
  'OR': { fillColor: defaultFill, value: 56 },
  'PA': { fillColor: defaultFill, value: 65 },
  'RI': { fillColor: defaultFill, value: 25 },
  'SC': { fillColor: defaultFill, value: 45 },
  'SD': { fillColor: defaultFill, value: 19 },
  'TN': { fillColor: defaultFill, value: 48 },
  'TX': { fillColor: defaultFill, value: 80 },
  'UT': { fillColor: defaultFill, value: 25 },
  'VT': { fillColor: defaultFill, value: 23 },
  'VA': { fillColor: defaultFill, value: 69 },
  'WA': { fillColor: defaultFill, value: 60 },
  'WV': { fillColor: defaultFill, value: 20 },
  'WI': { fillColor: defaultFill, value: 34 },
  'WY': { fillColor: defaultFill, value: 18 }
};

export default statesDefaults;
